// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvsN4-LXu22BzYAel1lF5OV5U6w6Bkq14',
    appId: '1:419935836553:web:c1eb904381fd68d2b12958',
    messagingSenderId: '419935836553',
    projectId: 'hotel-booking-1dd17',
    authDomain: 'hotel-booking-1dd17.firebaseapp.com',
    storageBucket: 'hotel-booking-1dd17.firebasestorage.app',
    measurementId: 'G-H2Q5RPDG7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXmSUWyTNacDxmTYPbgq-nIf1nJpVc3G0',
    appId: '1:419935836553:android:8376b2cee96f5c43b12958',
    messagingSenderId: '419935836553',
    projectId: 'hotel-booking-1dd17',
    storageBucket: 'hotel-booking-1dd17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXz5MYUBjYohWPCnPKCZCxI3Sn6rvIfWM',
    appId: '1:419935836553:ios:1da68b5a5ee78d59b12958',
    messagingSenderId: '419935836553',
    projectId: 'hotel-booking-1dd17',
    storageBucket: 'hotel-booking-1dd17.firebasestorage.app',
    iosBundleId: 'com.example.exam4OyDemo',
  );
}
